# Generated by Django 5.0.7 on 2024-08-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_meshsettings_check_download_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='type',
        ),
        migrations.AddField(
            model_name='mesh',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('ok', 'Ok')], default='unknown', help_text='The health status of this mesh', max_length=16),
        ),
        migrations.AlterField(
            model_name='node',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('ok', 'Ok')], default='unknown', help_text='The health status of this node. Even devices that are online may not be functioning correctly', max_length=16),
        ),
        migrations.AlterField(
            model_name='node',
            name='mesh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='monitoring.mesh'),
        ),
    ]
