# Generated by Django 5.0.7 on 2024-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_remove_alert_type_mesh_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshsettings',
            name='check_retransmission_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
